run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - bodyclose
    - noctx
    - prealloc

linters-settings:
  errcheck:
    check-type-assertions: true
  govet:
    enable-all: true
    disable:
      - fieldalignment
  goimports:
    local-prefixes: github.com/vibingsteamer/mcp-abap-adt-go
  misspell:
    ignore-words:
      - CLAS  # SAP object type abbreviation for class

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - unparam
    # Handler methods are called indirectly via universal tool router (handlers_universal.go)
    # The linter can't trace: handleUniversalTool -> handleUniversalRead -> handleGetTable
    - path: internal/mcp/(handlers_.*|server)\.go
      linters:
        - unused
    - path: internal/mcp/handlers_.*\.go
      linters:
        - unparam
    - path: internal/mcp/handlers_.*\.go
      linters:
        - staticcheck
      text: "U1000"
